name: Docker Build and Push
on:
  push:
    branches:
      - main
      - beta
      - alpha
  pull_request:
    branches:
      - main
      - beta
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - id: sanitize_tag
        name: Sanitize image tag
        run: echo tag=${raw_tag//\//-} >> $GITHUB_OUTPUT
        env:
          raw_tag: ${{ github.ref_name }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/Dockerfile.live
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/frontend:${{ steps.sanitize_tag.outputs.tag }}
            ghcr.io/${{ steps.string.outputs.lowercase }}/frontend:${{ steps.sanitize_tag.outputs.tag }}-${{ github.sha }}
          cache-from: ${{ !inputs.no_cache && 'type=gha' || '' }}
          cache-to: type=gha,mode=max
